### PR TITLE
Backport cloud image tests for RHEL 7

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by atodorov** [comment]
@bcl lots of pylint issues reported in Travis. Do we ignore or fix them ? Please see log.

**Comment by bcl** [comment]
We should figure out how to fix them. It looks like pylint is having trouble dealing with the response objects, calling them tuples instead of objects.

**Comment by bcl** [comment]
See this commit: https://github.com/bcl/lorax/commit/1f25aef6509d436c54cb0efa4e8487562025f798
It turns off the errors for the effected files.

**Comment by atodorov** [comment]
@bcl I cherry-picked the DataHolder commit becase of a traceback but even with it I still see a failure:

```
2018-12-13 13:41:56,540: traceback: Traceback (most recent call last):
  File "/var/lib/jenkins/lorax-rhel7-vmware-PR-runtest/src/pylorax/api/queue.py", line 142, in monitor
    make_compose(cfg, os.path.realpath(dst))
  File "/var/lib/jenkins/lorax-rhel7-vmware-PR-runtest/src/pylorax/api/queue.py", line 244, in make_compose
    run_creator(install_cfg, callback_func=cancel_build)
  File "/var/lib/jenkins/lorax-rhel7-vmware-PR-runtest/src/pylorax/creator.py", line 540, in run_creator
    disk_img = make_image(opts, ks, callback_func=callback_func)
  File "/var/lib/jenkins/lorax-rhel7-vmware-PR-runtest/src/pylorax/creator.py", line 426, in make_image
    novirt_install(opts, disk_img, disk_size, ks.handler.method.url, callback_func=callback_func)
  File "/var/lib/jenkins/lorax-rhel7-vmware-PR-runtest/src/pylorax/installer.py", line 331, in novirt_install
    elif opts.qcow2:
  File "/var/lib/jenkins/lorax-rhel7-vmware-PR-runtest/src/pylorax/base.py", line 64, in __getattr__
    raise AttributeError
AttributeError
```

The missing attribute is `qcow2`. This is when building a vmware image.

**Comment by bcl** [comment]
In compose.py ami, vhd, vmdk, openstack are all missing qcow2. Actually their options need to be updated to match this branch, they will be a bit different than the rhel8-branch

**Comment by bcl** [comment]
Give this a try - https://github.com/weldr/lorax/pull/552

**Comment by atodorov** [comment]
@bcl this is ready for review, although not everything works (reliably). Status and known issues:

* image build tests - PASS
* Azure tests - PASS
* OpenStack tests - PASS
* vmware tests - FAIL: VM guest can be provisioned and started but is not assigned an IP address. Maybe we're missing something in the kickstart file.
* AWS tests - FAIL: Uploading the image to S3 fails with RequestTimeTooSkewed error although I have ntp configured to use Amazon's servers. Couldn't reproduce on another system so not sure how to debug. 
* Sometimes downstream jobs will fail b/c they are trying to checkout the wrong commit number. This may be some sort of race condition in Jenkins or just a problem with us hitting API rate limits. If you restart the same jobs by hand they work fine. I've seen this most often with the Azure and OpenStack jobs. Not sure how to debug ATM.

**Pull request merged**
