### PR TITLE
tests: unskip Azure scenario

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by bcl** [comment]
Any idea why all those other tests failed?

Also, do you have any ideas as to how we could better manage things like this? I don't like seeing patches like this, it's making the history messy.

**Comment by chris1984** [comment]
rekicking jenkins

**Comment by atodorov** [comment]
> rekicking jenkins, +1 can we just override the all tests pass and leave a comment or something?

Jenkins is no more, not sure what you did.

**Comment by atodorov** [comment]
> Any idea why all those other tests failed?

Travis failed pylint which was related to my changes. Fixed.

A number of the other scenarios failed with 503 from the mirrors. I saw live-iso timed out.

> Also, do you have any ideas as to how we could better manage things like this? I don't like seeing patches like this, it's making the history messy.

Not really. If we move the code outside of the repository then PR-CI integration will become much harder. I don't see the problem here but this is something better discussed on the ML.

**Comment by chris1984** [comment]
> > rekicking jenkins, +1 can we just override the all tests pass and leave a comment or something?
> 
> Jenkins is no more, not sure what you did.

Sorry meant travis

**Comment by larskarlitski** [comment]
Nice to see this work again finally!

**Pull request merged**
