### PR TITLE
Backport additional tests for blueprints/compose

### PR DESCRIPTION
**Pull request by atodorov**
--- Description of proposed changes ---

Referenced bug still not approved.

--- Merge policy ---

- [x] Travis CI PASS
- [ ] `*-aws-runtest` PASS
- [ ] `*-azure-runtest` PASS
- [ ] `*-images-runtest` PASS
- [ ] `*-openstack-runtest` PASS
- [ ] `*-vmware-runtest` PASS
- [ ] For `rhel8-*` and `rhel7-*` branches commit log references an approved
  bug in Bugzilla. Do not merge if the bug doesn't have the 3 ACKs set to `+`!

--- Jenkins commands ---

- `ok to test` to accept this pull request for testing
- `test this please` for a one time test run
- `retest this please` to start a new build

### CODE REVIEW

**Comment by atodorov** [comment]
@bcl referenced bug has been approved, PR has been updated to what is in master. Please review again.

**Comment by bcl** [comment]
I don't think there's anything else to do for this. But the order of groups/modules looks like it makes the test fail. It should be:
    groups = []
    modules = []

**Comment by atodorov** [comment]
> ... the order of groups/modules looks like it makes the test fail. It should be:
> groups = []
> modules = []

@bcl checkout my latest commit here. Apparently `blueprints show` in RHEL7 scrambles the contents, which is not what we see on master and rhel8. If you think the latest commit is acceptable workaround I will squash it into the existing ones. Otherwise we probably need to treat this as a bug.

**Comment by atodorov** [comment]
@bcl I worked around the fact that TOML dicts on RHEL7 don't keep their ordering by adding a small script to compare 2 blueprints. Please review and merge if you are happy with the changes.

**Pull request merged**
