### PR TITLE
don't skip Xorg packages on s390x to allow local GUI installation under KVM

### PR DESCRIPTION
**Pull request by sharkcz**
related to https://bugzilla.redhat.com/show_bug.cgi?id=1727029

### CODE REVIEW

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by bcl** [comment]
Looks ok to me, but before I merge it we need to:
* make sure the packages are available in the s390 repo (where is it? I thought it was on alt, but can't track it down this morning)
* make sure someone has done a test build with this change
* make sure it doesn't break existing use cases

**Comment by sharkcz** [comment]
> Looks ok to me, but before I merge it we need to:
> 
>     * make sure the packages are available in the s390 repo (where is it? I thought it was on alt, but can't track it down this morning)

my PRs with the changes have been merged, no builds yet, it will be all in primary koji instance
 
>     * make sure someone has done a test build with this change

yes, will do
 
>     * make sure it doesn't break existing use cases

yes, will do

**Comment by sharkcz** [comment]
- the newly required packages (xorg-x11-drivers, tigervnc-server-module) are in the F-31 repos
- lorax successfully produces an image with the proposed change
- anaconda still starts (and runs) fine with the new content in install.img

**Pull request merged**
