### PR TITLE
Add prefixdevname to Anaconda image

### PR DESCRIPTION
**Pull request by msekletar**
Related: RHEL-30010

### CODE REVIEW

**Review by bcl — CHANGES_REQUESTED** [review]
Thanks for the PR, it needs a few changes:
* please don't edit the `lorax.spec`, that is done as part of the release process
* Refer the the Jira issue in the commit on a separate line as `Related: RHEL-30010`
* Also submit a template change to https://gitlab.com/redhat/centos-stream/rpms/lorax-templates-rhel which is the rhel/centos specific templates. No need to change anything else there, just the template and make sure the commit has the `Related` line.

**Comment by msekletar** [comment]
> Thanks for the PR, it needs a few changes:
> 
> * please don't edit the `lorax.spec`, that is done as part of the release process

I've dropped spec changes

> * Refer the the Jira issue in the commit on a separate line as `Related: RHEL-30010`

Issue reference is now (and was previously) on the separate line. However, when I am looking at the commit in Github UI I don't see empty line (but it is there) between issue reference and subject line.

> * Also submit a template change to https://gitlab.com/redhat/centos-stream/rpms/lorax-templates-rhel which is the rhel/centos specific templates. No need to change anything else there, just the template and make sure the commit has the `Related` line.

Will do.

Thank you for the review.

**Comment by msekletar** [comment]
> > * Also submit a template change to https://gitlab.com/redhat/centos-stream/rpms/lorax-templates-rhel which is the rhel/centos specific templates. No need to change anything else there, just the template and make sure the commit has the `Related` line.
> 
> Will do.

https://gitlab.com/redhat/centos-stream/rpms/lorax-templates-rhel/-/merge_requests/46

**Review by bcl — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
