### PR TITLE
Update Malayalam font to its new renamed package name rit-meera-new-fonts

### PR DESCRIPTION
**Pull request by pnemade**
I am submitting this PR as part of F36 Change https://fedoraproject.org/wiki/Changes/MalayalamDefaultFontsUpdate

Signed-off-by: Parag Nemade <pnemade@fedoraproject.org>

### CODE REVIEW

**Comment by pnemade** [comment]
Can someone please review this PR and merge it?

**Comment by bcl** [comment]
Is that really the only change needed? I thought that the `google-noto-serif-gurmukhi-fonts` would also need to be changed to `google-noto-serif-gurmukhi-vf-fonts` at the least.

**Comment by pnemade** [comment]
I just want to keep this commit for the Change submitted https://fedoraproject.org/wiki/Changes/MalayalamDefaultFontsUpdate and not to mix it with https://fedoraproject.org/wiki/Changes/DefaultToNotoFonts Change.

I think @tagoh will submit his change to lorax in another PR.

**Comment by bcl** [comment]
ah! Whoops, I totally missed that this was for a different change proposal :)

**Review by bcl — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
