### PR TITLE
runtime-install: wget2-wget has replaced wget

### PR DESCRIPTION
**Pull request by AdamWill**
wget has been retired:
https://src.fedoraproject.org/rpms/wget/c/ce69c17
in favor of wget2-wget:
https://fedoraproject.org/wiki/Changes/Wget2asWget

### CODE REVIEW

**Comment by AdamWill** [comment]
as this broke rawhide and bcl doesn't seem to be around rn, I'm doing a backport build so we can get a rawhide out.

**Comment by bcl** [comment]
Thanks for handling things. Why doesn't wget2-wget provide wget though? Seems like that's going to cause a whole bunch of confusion down the road.

**Comment by AdamWill** [comment]
it does provide it, but IIRC, lorax needs exact binary package names, it can't find them via provides. comps is similar.

**Comment by bcl** [comment]
> it does provide it, but IIRC, lorax needs exact binary package names, it can't find them via provides. comps is similar.

Lorax uses dnf to depsolve, it works fine with provides. Or should. Or did :) Maybe a dnf5 thing. I'm fine with the change, but I want to make sure there's not something else going on here first.

**Comment by AdamWill** [comment]
oh, huh, then that's weird. This is the Rawhide compose failure we were dealing with: [failed-composes issue](https://pagure.io/releng/failed-composes/issue/5865), [failed task](https://koji.fedoraproject.org/koji/taskinfo?taskID=112390239), [the actual failure](https://kojipkgs.fedoraproject.org//work/tasks/239/112390239/root.log). The backported patch did seem to fix it.

**Comment by bcl** [comment]
FTR I've filed #1372 to track this change in behavior.

**Review by bcl — APPROVED** [review]
ack

**Pull request merged**
