### PR TITLE
tests: Fail on script errors

### LINKED ISSUE #727: tests: We're not catching errors in test scripts
beakerlib doesn't seem to fail when there's an error in the test script. I'm not sure if we can just `set -e`, because that would kill the test process and might not produce the status report.

To reproduce, call an unknown command in one of the test scripts. I noticed it in https://github.com/weldr/lorax/pull/720

### PR DESCRIPTION
**Pull request by larskarlitski**
Fixes #727

### CODE REVIEW

**Comment by larskarlitski** [comment]
First bug found: `$BLUEPRINTS_DIR` was unbound in `test_cli.sh`.

I wonder how the `custom_cmdline_arg` tests were passing?

**Comment by larskarlitski** [comment]
Update: can't use `set -u` when sourcing beakerlib. It has unbound variables. Leaving `-e`.

**Comment by atodorov** [comment]
Obsoletes #714, #715, #716 for the $BLUEPRINTS_DIR change. The test looks OK.

**Comment by larskarlitski** [comment]
> Obsoletes #714, #715, #716 for the $BLUEPRINTS_DIR change. The test looks OK.

Oops sorry I didn't see those.

It looks like the change is breaking something on the Jenkins test runners. Is that why you haven't approved this yet?

By the way, I've opened https://github.com/beakerlib/beakerlib/issues/43.

**Pull request merged**
