### PR TITLE
fix typo in api docstring

### PR DESCRIPTION
**Pull request by ondrejbudai**
Just small mistake I encountered when implementing this API in osbuild-composer.

### CODE REVIEW

**Comment by chris1984** [comment]
@ondrejbudai can you rekick the tests so we can merge?

**Comment by ondrejbudai** [comment]
@chris1984 how can I do that?

**Comment by atodorov** [comment]
> @chris1984 how can I do that?

See `test/README.md`

**Comment by ondrejbudai** [comment]
Something went wrong. Any ideas?

```
bots/tests-trigger --repo weldr/lorax 911              
Traceback (most recent call last):
  File "bots/tests-trigger", line 88, in <module>
    sys.exit(main())
  File "bots/tests-trigger", line 84, in main
    return trigger_pull(api, opts)
  File "bots/tests-trigger", line 21, in trigger_pull
    if not opts.allow and login not in api.whitelist():
  File "/home/obudai/work/lorax/bots/task/github.py", line 383, in whitelist
    teamId = self.teamIdFromName(TEAM_CONTRIBUTORS)
  File "/home/obudai/work/lorax/bots/task/github.py", line 394, in teamIdFromName
    for team in self.get("/orgs/cockpit-project/teams") or []:
  File "/home/obudai/work/lorax/bots/task/github.py", line 259, in get
    raise GitHubError(self.qualify(resource), response)
task.github.GitHubError: Error accessing /orgs/cockpit-project/teams
  Status: 403
  Reason: Forbidden
  Response: {"message":"Must have admin rights to Repository.","documentation_url":"https://developer.github.com/v3/teams/#list-teams"}
```

**Pull request merged**
