### PR TITLE
test: Output results for cockpit's log.html

### PR DESCRIPTION
**Pull request by larskarlitski**
Cockpit's log.html has a peculiar format, but parsing logs in html is
much easier, because it shows expandable sections for each test.

I'll switch cockpit over to generating links to the html after this lands. Otherwise, we'll put the current logs through log.html, which might garble them.

Example: https://209.132.184.41:8493/logs/pull-12141-20190624-211212-54fc92b5-verify-fedora-30/log.html

### CODE REVIEW

**Comment by larskarlitski** [comment]
> Looks okay apart from the f-strings. But IMHO it would make sense to also add the log.html bits so that we can actually see the result and verify that the format is good.

Oh I thought passing `--html-output` to `tests-invoke` was all that's needed for that?

**Comment by martinpitt** [comment]
Travis failure:
```
************* Module /lorax/test/composertest.py
W0621(redefined-outer-name): 16,4: print_exception: Redefining name 'traceback' from outer scope (line 7)
W0404(reimported): 16,4: print_exception: Reimport 'traceback' (imported line 7)
```

**Comment by larskarlitski** [comment]
> Travis failure:

Yep, saw it. Fixed in the last push. I also removed all the f-strings :cry:

**Comment by martinpitt** [comment]
The [aws](https://209.132.184.41:8493/logs/pull-783-20190625-180909-70f318f6-cockpit-fedora-30-aws/log) and [openstack](https://209.132.184.41:8493/logs/pull-783-20190625-180909-70f318f6-cockpit-fedora-30-openstack/log) tests failed. These may be network flakes, retrying.

**Pull request merged**
