### PR TITLE
[don't merge] Fix VMware not consistent biosdevname issue

### PR DESCRIPTION
**Pull request by chris1984**
--- Description of proposed changes ---

PR to attempt to fix VMware tests and have the image pick up an IP

--- Merge policy ---

- [ ] Travis CI PASS
- [ ] `*-aws-runtest` PASS
- [ ] `*-azure-runtest` PASS
- [ ] `*-images-runtest` PASS
- [ ] `*-openstack-runtest` PASS
- [ ] `*-vmware-runtest` PASS
- [ ] For `rhel8-*` and `rhel7-*` branches commit log references an approved
  bug in Bugzilla. Do not merge if the bug doesn't have the 3 ACKs set to `+`!

--- Jenkins commands ---

- `ok to test` to accept this pull request for testing
- `test this please` for a one time test run
- `retest this please` to start a new build

### CODE REVIEW

**Comment by atodorov** [comment]
@chris1984 even with this change the VM started by Jenkins fails to get an IP address. Keep it open, we will be able to test in a different CI environment very soon.

**Comment by chris1984** [comment]
@atodorov it is odd it fails, every time i run it on my local machine with tests

**Comment by atodorov** [comment]
Root cause may be related to https://bugzilla.redhat.com/show_bug.cgi?id=1710877 and this PR is not going to fix it.

**Comment by atodorov** [comment]
The root cause here seems to be fixed by https://github.com/weldr/lorax/pull/766 where we can see a passing result from Jenkins vmware job. Closing.

**Pull request closed without merging**
