### PR TITLE
[7.9] Add test for running composer with --no-system-repos option

### PR DESCRIPTION
**Pull request by atodorov**
- add test coverage for rhbz#1650363
- cherry-picked from 5322664432631f61af831d1eef5f400ffb65b3f9

Related: rhbz#1785159

### CODE REVIEW

**Comment by atodorov** [comment]
@bcl PR #526 which added this functionality has been labeled as `rhel7-extras` but I don't think it made it to this branch. Can you give more info on what happened/was intended to happen?

**Comment by bcl** [comment]
> @bcl PR #526 which added this functionality has been labeled as `rhel7-extras` but I don't think it made it to this branch. Can you give more info on what happened/was intended to happen?

I think I meant to make a bug to cover backporting it, but never did. Guess I'll do that now.

**Comment by atodorov** [comment]
> > @bcl PR #526 which added this functionality has been labeled as `rhel7-extras` but I don't think it made it to this branch. Can you give more info on what happened/was intended to happen?
> 
> I think I meant to make a bug to cover backporting it, but never did. Guess I'll do that now.

https://bugzilla.redhat.com/show_bug.cgi?id=1785388

**Comment by atodorov** [comment]
I've tested this today manually with lorax-composer-19.7.40-1.el7_9.x86_64 and it passes. CI job for 7.9 will likely pass after an image refresh.

@bcl feel free to merge if you want.

**Pull request merged**
