### PR TITLE
Backport changes for Cockpit CI to RHEL 7

### PR DESCRIPTION
**Pull request by atodorov**
RelatedL rhbz#1698366

I did a diff against master and dropped unrelated patches.

@larskarlitski I'm not sure if `check-api` will work on RHEL 7.

### CODE REVIEW

**Comment by atodorov** [comment]
@larskarlitski, @martinpitt - from what I can see we fail at sfdisk trying to extend the root partition size. Any advice ?

**Comment by bcl** [comment]
composertest.py needs to be backported to py2, it is using python 3.6 features like f"string", and list expansion with *extra_env

**Comment by atodorov** [comment]
> composertest.py needs to be backported to py2, it is using python 3.6 features like f"string", and list expansion with *extra_env

@bcl thanks for spotting this. updated.

**Comment by larskarlitski** [comment]
> composertest.py needs to be backported to py2, it is using python 3.6 features like f"string", and list expansion with *extra_env

`composertest.py` runs in the test container, not inside the VM. It's the script that spins up the VM itself. There's no need for it to be ported.

**Comment by atodorov** [comment]
> composertest.py runs in the test container, not inside the VM. It's the script that spins up the VM itself. There's no need for it to be ported.

I kept the shebang but didn't revert the rest of the changes b/c pylint will find this file and complain about it!

**Pull request merged**
