### PR TITLE
Update the lorax templates to match what lorax provides

### PR DESCRIPTION
**Pull request by bcl**
lorax-creator doesn't ship these, but it uses them for running tests, so
make sure they are current.

Related: rhbz#1689314

### CODE REVIEW

**Comment by atodorov** [comment]
With qcow2 test executed by hand:

```
[   PASS   ] :: Can't ssh to 'localhost' as root using password-based auth (Expected 0, got 0)

[   FAIL   ] :: root account is disabled in /etc/shadow (Expected 0, got 255)
[   FAIL   ] :: audit.log contains entry about unsuccessful root login (Expected 0, got 255)
[   FAIL   ] :: Login with empty passwords is disabled in sshd config file (Expected 1, got 255)
[   FAIL   ] :: Command 'ssh -o StrictHostKeyChecking=no -i /tmp/composer-ssh-keys.ritns8/id_rsa -p 2222 root@localhos)
[   FAIL   ] :: System booted from the image contains specified parameter on kernel command line (Expected 0, got 255)
```

But the same thing passes in Jenkins.


For live-iso we got 
```
2019-06-18 20:39:33,296: Truncating isolabel to 32 chars: Red Hat Enterprise Linux 7 x86_6
2019-06-18 20:39:33,296: Rebuilding initrds
2019-06-18 20:39:33,297: dracut args = ['--xz', '--add', 'livenet dmsquash-live convertfs pollcdrom', '--omit', 'plymouth', '--no-hostonly', '--no-early-microcode']
2019-06-18 20:39:33,299: rebuilding boot/initramfs-3.10.0-1055.el7.x86_64.img

No '/dev/log' or 'logger' included for syslog logging

/bin/sed: can't read /proc/cpuinfo: No such file or directory
/bin/sed: can't read /proc/cpuinfo: No such file or directory
/bin/sed: can't read /proc/cpuinfo: No such file or directory
/bin/sed: can't read /proc/cpuinfo: No such file or directory

:: [ 20:39:49 ] :: [   INFO   ] :: Waiting for compose to finish ...

:: [ 20:40:09 ] :: [   INFO   ] :: Waiting for compose to finish ...

:: [ 20:40:29 ] :: [   INFO   ] :: Waiting for compose to finish ...

2019-06-18 20:40:38,408: Building boot.iso
2019-06-18 20:40:38,657: 

Traceback (most recent call last):
  File "/var/lib/jenkins/lorax-rhel7-images-PR-runtest/src/pylorax/ltmpl.py", line 56, in parse
    textbuf = template.render(**variables)
  File "/usr/lib/python2.7/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 815, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 841, in _exec_template
    callable_(context, *args, **kwargs)
TypeError: render_body() takes exactly 8 arguments (7 given)

2019-06-18 20:40:43,714: traceback: Traceback (most recent call last):
  File "/var/lib/jenkins/lorax-rhel7-images-PR-runtest/src/pylorax/api/queue.py", line 142, in monitor
    make_compose(cfg, os.path.realpath(dst))
  File "/var/lib/jenkins/lorax-rhel7-images-PR-runtest/src/pylorax/api/queue.py", line 244, in make_compose
    run_creator(install_cfg, cancel_func=cancel_build)
  File "/var/lib/jenkins/lorax-rhel7-images-PR-runtest/src/pylorax/creator.py", line 563, in run_creator
    result_dir = make_livecd(opts, mount_dir, work_dir)
  File "/var/lib/jenkins/lorax-rhel7-images-PR-runtest/src/pylorax/creator.py", line 355, in make_livecd
    tb.build()
  File "/var/lib/jenkins/lorax-rhel7-images-PR-runtest/src/pylorax/treebuilder.py", line 241, in build
    self._runner.run(templatefile, kernels=self.kernels)
  File "/var/lib/jenkins/lorax-rhel7-images-PR-runtest/src/pylorax/ltmpl.py", line 187, in run
    commands = t.parse(templatefile, variables)
  File "/var/lib/jenkins/lorax-rhel7-images-PR-runtest/src/pylorax/ltmpl.py", line 56, in parse
    textbuf = template.render(**variables)
  File "/usr/lib/python2.7/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 815, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 841, in _exec_template
    callable_(context, *args, **kwargs)
TypeError: render_body() takes exactly 8 arguments (7 given)

```

**Comment by bcl** [comment]
What version of lorax do these builders have? They should be running 19.7.25-1

For the first, I think we can make it consistently not ask for password if we also pass `-o PasswordAuthentication=no`

**Comment by bcl** [comment]
> For the first, I think we can make it consistently not ask for password if we also pass `-o PasswordAuthentication=no`

And I now realize that defeats the purpose of having the test :) So I'm not sure what to do about that when running it locally.

**Comment by bcl** [comment]
Looks like the aws test problem is a credentials issue. For tests like that it might be a good idea to do a test of the service before spending the time building the image so that it will fail faster.

**Comment by atodorov** [comment]
> Looks like the aws test problem is a credentials issue. 

@larskarlitski, @martinpitt - can you take a look? IIRC we use the same credentials as in Jenkins so not sure what's going on in AWS.

**Comment by atodorov** [comment]
@bcl the AWS problem is the `RequestTimeTooSkewed` which happens when the host system time gets out of sync with Amazon despite us having enabled NTP. 100% reproducible in Jenkins, but locally very rarely.

**Comment by martinpitt** [comment]
Indeed the clocks on our CI machines are off by as much as 15 minutes. Due to some ridiculous firewalling, NTP cannot be used there. I manually updated the time on all of them, let's see if that works better now.

**Pull request merged**
