### PR TITLE
New test: test qcow2 image with KVM

### PR DESCRIPTION
**Pull request by atodorov**
--- Description of proposed changes ---

- Build the compose
- Try to launch a VM with virt-install (QEMU-KVM)

--- Merge policy ---

- [ ] Travis CI PASS
- [ ] `*-aws-runtest` PASS
- [ ] `*-azure-runtest` PASS
- [ ] `*-images-runtest` PASS
- [ ] `*-openstack-runtest` PASS
- [ ] `*-vmware-runtest` PASS
- [ ] For `rhel8-*` and `rhel7-*` branches commit log references an approved
  bug in Bugzilla. Do not merge if the bug doesn't have the 3 ACKs set to `+`!

--- Jenkins commands ---

- `ok to test` to accept this pull request for testing
- `test this please` for a one time test run
- `retest this please` to start a new build

### CODE REVIEW

**Comment by bcl** [comment]
It may be easier to do this with qemu-kvm, with virt-install you need to have the big pile of libvirt related packages installed and the service running. You can use `-netdev ... hostfwd=tcp::2222-:22` so that you don't need to search for the IP, just ssh to 2222 on localhost to connect to it.

**Comment by atodorov** [comment]
> It may be easier to do this with qemu-kvm, with virt-install you need to have the big pile of libvirt related packages installed and the service running. You can use -netdev ... hostfwd=tcp::2222-:22 so that you don't need to search for the IP, just ssh to 2222 on localhost to connect to it.

This was my original implementation and the parts how I fetch the VM IP address eluded me. Will update.

**Comment by atodorov** [comment]
Running this test manually gives me:

```
2019-02-25 06:07:05,049: The installation was stopped due to an error which occurred while running in non-interactive cmdline mode. Since there cannot be any questions in cmdline mode, edit your kickstart file and retry installation.
2019-02-25 06:07:05,049: The exact error message is:
2019-02-25 06:07:05,050: 
2019-02-25 06:07:05,050: The following mandatory spokes are not completed:
2019-02-25 06:07:05,051: Installation Destination.
2019-02-25 06:07:05,051: 
2019-02-25 06:07:05,051: The installer will now terminate.
2019-02-25 06:07:05,458: Running anaconda failed: process '['unshare', '--pid', '--kill-child', '--mount', '--propagation', 'unchanged', 'anaconda', '--kickstart', '/var/lib/lorax/composer/results/de4aa50d-f615-445c-8f3e-7cc738873163/final-kickstart.ks', '--cmdline', '--loglevel', 'debug', '--image', '/var/lib/lorax/composer/results/de4aa50d-f615-445c-8f3e-7cc738873163/compose/disk.qcow2', '--remotelog', '127.0.0.1:50053']' exited with status 1
```

**Comment by bcl** [comment]
> Running this test manually gives me:

Not enough detail there to debug that. The anaconda logs should reveal why it couldn't setup the destination.

**Comment by atodorov** [comment]
@bcl: I retested again on Fedora 29 to get you the logs b/c the previous system was destroyed. The result was PASS, qcow2 compose was built and I saw qemu-kvm booting up successfully and the test script reporting PASS.

Review/merge at will. I will go ahead and port to the other branches.

**Pull request merged**
