### PR TITLE
drop Apple/HFS bits from the templates

### PR DESCRIPTION
**Pull request by sharkcz**
--- Description of proposed changes ---
Drop the remaining non-ppc64le bits from the templates. Make the ISO creation
work with xorriso.

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1676411

--- Merge policy ---

- [x] Travis CI PASS
- [ ] `*-aws-runtest` PASS
- [ ] `*-azure-runtest` PASS
- [ ] `*-images-runtest` PASS
- [ ] `*-openstack-runtest` PASS
- [ ] `*-vmware-runtest` PASS
- [ ] For `rhel8-*` and `rhel7-*` branches commit log references an approved
  bug in Bugzilla. Do not merge if the bug doesn't have the 3 ACKs set to `+`!

--- Jenkins commands ---

- `ok to test` to accept this pull request for testing
- `test this please` for a one time test run
- `retest this please` to start a new build

### CODE REVIEW

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by atodorov** [comment]
Can one of the admins verify this patch?

**Comment by sharkcz** [comment]
@atodorov , what's wrong with your bot? I see 10+ same comments.

**Comment by bcl** [comment]
ok to test

**Pull request merged**
