### PR TITLE
WIP: Test anaconda scratch build for AWS

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by martinpitt** [comment]
There's something weird going on with the tests for this PR. They are being queued, and processed, but then nothing happens. I'm currently investigating this manually, and it seems that our sink is running into `Connection to 209.132.184.41 port 22 timed out`. That's our fedorainfracloud instance, I'm investigating what's going on.

**Comment by martinpitt** [comment]
OK, that's better. I moved our infra to an alternative log sink, and will dissect/reinstall the broken machine.

**Comment by atodorov** [comment]
@bcl the scratch build appears to work. AWS scenario here reports pass while still hitting the RequestTimeTooSkewed error when using older versions of anaconda, see:

https://fedorapeople.org/groups/cockpit/logs/pull-909-20191121-093333-1efb558b-weldr-lorax--rhel-7-8-aws/log.html - FAIL

https://fedorapeople.org/groups/cockpit/logs/pull-907-20191121-090101-e0d55748-weldr-lorax--rhel-7-8-aws/log.html - PASS

**Comment by atodorov** [comment]
this PR is past its usefulness. We know newer anaconda builds fixed the problem we were seeing in AWS so closing.

**Pull request closed without merging**
