### PR TITLE
More cleanup

### PR DESCRIPTION
**Pull request by AdamWill**
This is a grab-bag of changes to save more space in the runtime environment. Each commit has details. I've tested that I can at least build an image successfully, boot it, and run an install with these changes, and the help screen works. I didn't test wireless networking or extlinux bootloader install yet, though.

### CODE REVIEW

**Review by bcl — DISMISSED** [review]
Looks good, works fine.

**Review by bcl — APPROVED** [review]
Trying again... Used the github edit tool to fix the merge conflict.

**Comment by AdamWill** [comment]
I can rebase it now you've merged the others...

**Comment by AdamWill** [comment]
Can we merge this now?

**Review by bcl — APPROVED** [review]
Looks good to me. test failures seem to be a dnf change in rawhide, unrelated to this.

**Comment by bcl** [comment]
Wouldn't let me merge, so I cherry picked them to master.

**Comment by AdamWill** [comment]
Huh, weird. Fine by me. I'll send a PR to put the reproducibility thing back in in a few hours.

**Pull request closed without merging**
